blank_issues_enabled: true
contact_links:
  - name: PR
    url: https://github.com/multiformats/github-mgmt/edit/master/github/multiformats.yml
    about: Propose GitHub configuration change by modifying multiformats.yml
