name: Update

on:
  workflow_run:
    workflows:
      - "Apply"
    types:
      - completed
  workflow_dispatch:

jobs:
  update:
    name: Update
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      GITHUB_APP_ID: ${{ secrets.RW_GITHUB_APP_ID }}
      GITHUB_APP_INSTALLATION_ID: ${{ secrets[format('RW_GITHUB_APP_INSTALLATION_ID_{0}', matrix.workspace)] }}
      GITHUB_APP_PEM_FILE: ${{ secrets.RW_GITHUB_APP_PEM_FILE }}
    steps:
      - name: Generate app token
        id: token
        uses: tibdex/github-app-token@7ce9ffdcdeb2ba82b01b51d6584a6a85872336d4 # v1.5.1
        with:
          app_id: ${{ secrets.RW_GITHUB_APP_ID }}
          installation_id: ${{ secrets[format('RW_GITHUB_APP_INSTALLATION_ID_{0}', github.repository_owner)] }}
          private_key: ${{ secrets.RW_GITHUB_APP_PEM_FILE }}
      - name: Update PRs
        env:
          GITHUB_TOKEN: ${{ steps.token.outputs.token }}
        run: |
          while read number; do
            if [[ ! -z "$number" ]]; then
              if ! gh api -X PUT "/repos/${{ github.repository }}/pulls/$number/update-branch"; then
                echo "::warning title=update-branch failure::${{github.repository}}#$number"
              fi
            fi
          done <<< "$(gh api '/repos/${{ github.repository }}/pulls' --jq '.[] | .number')"
